server:
  port: 8081
logging:
  level:
    org.springframework: ERROR
    com.ourcompany: DEBUG
  file:
    name: "logs/notes-service.log"

spring:
  profiles:
    active: development
  main:
    banner-mode: off
  data:
    mongodb:
      host: localhost
      port: 27017
      database: notes

  application:
    name: notes-service
  config:
    import: optional:configserver:http://localhost:8888


  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      appname: NOTES-SERVICE