server:
  port: 8989

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: notes
          uri: lb://NOTES-SERVICE/notes
          predicates:
            - Path=/notes/**
        - id: reminder
          uri: lb://REMINDERS-SERVICE/reminders
          predicates:
            - Path=/reminders/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/